name: Test
on: [push]
jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Test
        env:
          CGO_ENABLED: 0
        run: go test ./...

      - name: Test Race
        run: go test -race ./...
